### ISSUE TITLE
refactor: 공용 인풋 피드백 반영

### ISSUE THREAD

**Issue by 21ow** [21ow/codeit-FE10-3-Mogazoa#33]
## 📝 Description

- 멘토링 피드백 사항 반영

## ✅ To-Dos

- [x] 코드 분리
- [x] input type 수정
- [x] props 제거 후 기본값 설정
- [x] id 동적 생성
