### ISSUE TITLE
fix: 모달 수정

### ISSUE THREAD

**Issue by changhui-chan** [21ow/codeit-FE10-3-Mogazoa#48]
## 📝 Description

모달 버그 수정

## ✅ To-Dos

- [x]  module css에 variable로 컬러 설정한 부분 없애기.
- [x] module css의 import방식 잘못된 부분 해결
- [x] createPortal로 모달 불러올 시, 애니메이션이 의도치 않게 작동되는 부분 해
